export const UI_START_OVERLAY_LOADING = 'UI_START_OVERLAY_LOADING';
export const UI_STOP_OVERLAY_LOADING = 'UI_STOP_OVERLAY_LOADING';

export const UI_START_FORM_LOADING = 'UI_START_FORM_LOADING';
export const UI_STOP_FORM_LOADING = 'UI_STOP_FORM_LOADING';

